### ISSUE TITLE
dpkg: warning: version 'rewrite-2' has bad syntax: version number does not start with digit

### ISSUE THREAD

**Issue by doc-jay** [whiskerz007/ubnt_get_wireguard#11]
Ran the script today and it removed the wireguard module and could not restore the running config.  Ended with a 'commit failed'..

`admin@sanatized:/config/scripts$ sudo ./get_wireguard.sh
[INFO] Board model: EdgeRouter 6P
[INFO] Board type: e300
[INFO] Board repo mapping: e300
[INFO] Firmware version: v2.0.9.5346345.201028.1647
[INFO] Installed WireGuard version: 1.0.20201112-1
[INFO] Release version: rewrite-2
dpkg: warning: version 'rewrite-2' has bad syntax: version number does not start with digit
[INFO] Debian package URL: https://github.com/WireGuard/wireguard-vyatta-ubnt/releases/download/rewrite-2/e300-v2-v1.0.20201221-v1.0.20200827.deb
Downloading WireGuard package...
Checking WireGuard package integrity...
Backing up running configuration...
Removing running WireGuard configuration...
Removing WireGuard module...
Installing WireGuard...
Restoring previous running configuration...
[ interfaces wireguard wg0 description WG peer - peer1 ]
Cannot find device "wg0"

[ interfaces wireguard wg1 description WG peer - peer2 ]
Cannot find device "wg1"

[ interfaces wireguard wg2 description peer3 ]
Cannot find device "wg2"

Commit failed
[ERROR] 1@228 Unknown failure occured.`

**Comment by doc-jay** [comment]
If I run './get_wireguard.sh 1.0.20201221-1' it will reinstall successfully

**Comment by whiskerz007** [comment]
I would suggest you grab the latest version of the script. The script you are using will always install the latest release and does not check if it is a prerelease or not. The newest script will filter out the prerelease packages when the version isn't specified. 

`dpkg: warning` is expected and okay. This is due to the naming schema used when compiling the package.

The errors you are receiving when setting the description for the interfaces has been corrected with whiskerz007/wireguard-vyatta-ubnt@c5f134c.
